/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.mainmenu;

/**
 *
 * @author Jefferson
 */
public class ManagerMenu extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public ManagerMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImagem = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnPayInstallments = new javax.swing.JButton();
        btnDocumentsInspection = new javax.swing.JButton();
        btnMembersList = new javax.swing.JButton();
        btnPlanSubscription = new javax.swing.JButton();
        lbMembersList = new javax.swing.JLabel();
        lbPlanSubscription = new javax.swing.JLabel();
        lbMembersList2 = new javax.swing.JLabel();
        lbMembersList3 = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoPequena.png"))); // NOI18N

        btnVoltar.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        btnVoltar.setText("Voltar");

        btnPayInstallments.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnPayInstallments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/employees.png"))); // NOI18N
        btnPayInstallments.setText("Lista de funcionários");
        btnPayInstallments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayInstallmentsActionPerformed(evt);
            }
        });

        btnDocumentsInspection.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnDocumentsInspection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/calendar.png"))); // NOI18N
        btnDocumentsInspection.setText("Especificações dos planos");
        btnDocumentsInspection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocumentsInspectionActionPerformed(evt);
            }
        });

        btnMembersList.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnMembersList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/monetary.png"))); // NOI18N
        btnMembersList.setText("Balanço geral");
        btnMembersList.setToolTipText("");
        btnMembersList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMembersListActionPerformed(evt);
            }
        });

        btnPlanSubscription.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnPlanSubscription.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/agreement.png"))); // NOI18N
        btnPlanSubscription.setText("Aferição de documentos");
        btnPlanSubscription.setToolTipText("");

        lbMembersList.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lbMembersList.setText("<html>Este menu contém todas as movimentações financeiras da academia. Você pode visualizar as receitas e gerenciar novas despesas neste menu.<br>Por aqui você pode acessar os resultados do caixa de determinado período e emitir relatórios financeiros que serão úteis para controle do negócio.</html>");

        lbPlanSubscription.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lbPlanSubscription.setText("<html>Este menu dá acesso a todos os documentos registrados pela academia, tanto de funcionários como de alunos.</html>");

        lbMembersList2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lbMembersList2.setText("<html>Esta é uma lista completa dos funcionários da academia. Por aqui você pode visualizar, editar, excluir e adicionar funcionários contratados.</html>");

        lbMembersList3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lbMembersList3.setText("<html>Este é o menu que contém todos os dados relacionados aos planos de pagamento.<br>Você pode usar este menu para adicionar/remover planos e também para editar informações, como o valor integral, nome, etc.</html>");

        lbTitle.setFont(new java.awt.Font("Cambria", 1, 30)); // NOI18N
        lbTitle.setText("Gestor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMembersList, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPayInstallments, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lbMembersList2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lbMembersList, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbMembersList3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPlanSubscription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbPlanSubscription, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGap(111, 111, 111))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDocumentsInspection, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVoltar)
                            .addComponent(lbImagem)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(505, 505, 505)
                        .addComponent(lbTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbImagem)
                .addGap(3, 3, 3)
                .addComponent(lbTitle)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPlanSubscription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMembersList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPlanSubscription, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 106, Short.MAX_VALUE))
                    .addComponent(lbMembersList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPayInstallments, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbMembersList2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDocumentsInspection, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbMembersList3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayInstallmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayInstallmentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPayInstallmentsActionPerformed

    private void btnDocumentsInspectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocumentsInspectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDocumentsInspectionActionPerformed

    private void btnMembersListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMembersListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMembersListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocumentsInspection;
    private javax.swing.JButton btnMembersList;
    private javax.swing.JButton btnPayInstallments;
    private javax.swing.JButton btnPlanSubscription;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JLabel lbMembersList;
    private javax.swing.JLabel lbMembersList2;
    private javax.swing.JLabel lbMembersList3;
    private javax.swing.JLabel lbPlanSubscription;
    private javax.swing.JLabel lbTitle;
    // End of variables declaration//GEN-END:variables
}
