/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.mainmenu;

/**
 *
 * @author Jefferson
 */
public class ManagerMenu extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public ManagerMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImagem = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnPayInstallments = new javax.swing.JButton();
        btnDocumentsInspection = new javax.swing.JButton();
        btnMembersList = new javax.swing.JButton();
        btnPlanSubscription = new javax.swing.JButton();
        lbMembersList = new javax.swing.JLabel();
        lbPlanSubscription = new javax.swing.JLabel();
        lbMembersList2 = new javax.swing.JLabel();
        lbMembersList3 = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoPequena.png"))); // NOI18N

        btnVoltar.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        btnVoltar.setText("Voltar");

        btnPayInstallments.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnPayInstallments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/debit-card.png"))); // NOI18N
        btnPayInstallments.setText("Pagamento de parcelas");
        btnPayInstallments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayInstallmentsActionPerformed(evt);
            }
        });

        btnDocumentsInspection.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnDocumentsInspection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/agreement.png"))); // NOI18N
        btnDocumentsInspection.setText("Aferição de documentos");
        btnDocumentsInspection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocumentsInspectionActionPerformed(evt);
            }
        });

        btnMembersList.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnMembersList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registration.png"))); // NOI18N
        btnMembersList.setText("Registro dos alunos");
        btnMembersList.setToolTipText("");
        btnMembersList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMembersListActionPerformed(evt);
            }
        });

        btnPlanSubscription.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnPlanSubscription.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/calendar.png"))); // NOI18N
        btnPlanSubscription.setText("Assinatura de Planos");
        btnPlanSubscription.setToolTipText("");

        lbMembersList.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lbMembersList.setText("<html>Este menu contém o registro de todos os alunos da academia.<br> Aqui você pode pesquisar, visualizar, excluir, alterar dados e matricular novos alunos.</html>");

        lbPlanSubscription.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lbPlanSubscription.setText("<html>Nesse menu você pode assinar um plano de pagamento para um aluno, emitindo um contrato e gerando as parcelas a serem pagas.</html>");

        lbMembersList2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lbMembersList2.setText("<html>Neste menu você pode visualizar todo o histórico de pagamentos recebidos ou pendentes e quitar parcelas que ainda não foram pagas pelos alunos.</html>");

        lbMembersList3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lbMembersList3.setText("<html>Por meio deste menu, você pode visualizar todos os documentos associados a um aluno e imprimir.<br> Aqui estão inclusos contratos de vínculo, contratos de assinatura de planos e recibos.</html>");

        lbTitle.setFont(new java.awt.Font("Cambria", 1, 30)); // NOI18N
        lbTitle.setText("Recepcionista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnMembersList, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(lbMembersList, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnPayInstallments, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lbMembersList2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPlanSubscription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbPlanSubscription, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGap(111, 111, 111))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDocumentsInspection, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbMembersList3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVoltar)
                            .addComponent(lbImagem)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(447, 447, 447)
                        .addComponent(lbTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbImagem)
                .addGap(16, 16, 16)
                .addComponent(lbTitle)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMembersList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMembersList, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPayInstallments, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbMembersList2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDocumentsInspection, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbMembersList3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(83, 83, 83)
                        .addComponent(btnVoltar)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPlanSubscription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPlanSubscription, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayInstallmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayInstallmentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPayInstallmentsActionPerformed

    private void btnDocumentsInspectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocumentsInspectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDocumentsInspectionActionPerformed

    private void btnMembersListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMembersListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMembersListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocumentsInspection;
    private javax.swing.JButton btnMembersList;
    private javax.swing.JButton btnPayInstallments;
    private javax.swing.JButton btnPlanSubscription;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JLabel lbMembersList;
    private javax.swing.JLabel lbMembersList2;
    private javax.swing.JLabel lbMembersList3;
    private javax.swing.JLabel lbPlanSubscription;
    private javax.swing.JLabel lbTitle;
    // End of variables declaration//GEN-END:variables
}
