/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.membercrud;

/**
 *
 * @author Jefferson
 */
public class FinalizeRegistration extends javax.swing.JFrame {
    
    /**
     * Creates new form ConfirmarDadosAluno
     */
    public FinalizeRegistration() {        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogo = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        lbMessage = new javax.swing.JLabel();
        btnEnrollmentPayment = new javax.swing.JButton();
        lbContractStatus = new javax.swing.JLabel();
        lbEnrollmentStatus = new javax.swing.JLabel();
        btnIssueContract = new javax.swing.JButton();
        lbEnrollmentCheck = new javax.swing.JLabel();
        lbContractCheck = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoPequena.png"))); // NOI18N

        btnBack.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        btnBack.setText("Voltar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnConfirm.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/confirm.png"))); // NOI18N
        btnConfirm.setText("Confirmar");
        btnConfirm.setEnabled(false);

        lbMessage.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lbMessage.setText("<html>Atenção funcionário: Emita o contrato para o cliente vincular-se à academia e também receba o pagamento da taxa de matrícula. <br>Quando concluir essas etapas, confirme a operação e o aluno estará livre para acessar a academia.</html>");

        btnEnrollmentPayment.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnEnrollmentPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/debit-card.png"))); // NOI18N
        btnEnrollmentPayment.setText("<html>Pagar taxa de<br> matrícula</html>");
        btnEnrollmentPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollmentPaymentActionPerformed(evt);
            }
        });

        lbContractStatus.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lbContractStatus.setText("Status do contrato:");

        lbEnrollmentStatus.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lbEnrollmentStatus.setText("Status da taxa de matrícula:");

        btnIssueContract.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnIssueContract.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agreement.png"))); // NOI18N
        btnIssueContract.setText("Emitir contrato");
        btnIssueContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueContractActionPerformed(evt);
            }
        });

        lbEnrollmentCheck.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lbEnrollmentCheck.setForeground(new java.awt.Color(255, 51, 51));
        lbEnrollmentCheck.setText("Pendente");

        lbContractCheck.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lbContractCheck.setForeground(new java.awt.Color(255, 51, 51));
        lbContractCheck.setText("Pendente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirm)
                        .addGap(26, 26, 26))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIssueContract, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(btnEnrollmentPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lbContractStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbContractCheck)
                .addGap(104, 104, 104)
                .addComponent(lbEnrollmentStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbEnrollmentCheck)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnLogo)
                .addGap(21, 21, 21)
                .addComponent(lbMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIssueContract, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnrollmentPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbContractStatus)
                    .addComponent(lbContractCheck)
                    .addComponent(lbEnrollmentStatus)
                    .addComponent(lbEnrollmentCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnConfirm))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIssueContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueContractActionPerformed
        
    }//GEN-LAST:event_btnIssueContractActionPerformed

    private void btnEnrollmentPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollmentPaymentActionPerformed
        
    }//GEN-LAST:event_btnEnrollmentPaymentActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       
    }//GEN-LAST:event_btnBackActionPerformed
    
 
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnEnrollmentPayment;
    private javax.swing.JButton btnIssueContract;
    private javax.swing.JLabel btnLogo;
    private javax.swing.JLabel lbContractCheck;
    private javax.swing.JLabel lbContractStatus;
    private javax.swing.JLabel lbEnrollmentCheck;
    private javax.swing.JLabel lbEnrollmentStatus;
    private javax.swing.JLabel lbMessage;
    // End of variables declaration//GEN-END:variables
}
