/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.membercrud;

import model.Member;
import model.PaymentPlan;

/**
 *
 * @author Jefferson
 */
public class FinalizeRegistration extends javax.swing.JFrame {
    
    private Member member;
    private PaymentPlan paymentPlan;
    
    /**
     * Creates new form ConfirmarDadosAluno
     */
    public FinalizeRegistration(Member member, PaymentPlan paymentPlan) {
        this.member = member;
        this.paymentPlan = paymentPlan;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImagem = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        lbAviso = new javax.swing.JLabel();
        btnConfirmarPagamento = new javax.swing.JButton();
        btnConfirmarAssinatura = new javax.swing.JButton();
        lbTituloStatusContrato = new javax.swing.JLabel();
        lbTituloStatusPagamento = new javax.swing.JLabel();
        btnEmitirContrato = new javax.swing.JButton();
        btnEmitirRecibo = new javax.swing.JButton();
        lbStatusPagamentoEscrito = new javax.swing.JLabel();
        lbStatusContratoEscrito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoPequena.png"))); // NOI18N

        btnVoltar.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnConfirmar.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/confirm.png"))); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setEnabled(false);

        lbAviso.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbAviso.setText("<html>Atenção funcionário: Emita o contrato para o cliente vincular-se à academia e também receba o pagamento da taxa de matrícula. <br>Quando concluir essas etapas, confirme o pagamento, a assinatura do contrato e emita o recibo. <br> Após essas etapas você pode confirmar a inscrição do aluno e ele está livre para acessar a academia.</html>");

        btnConfirmarPagamento.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnConfirmarPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/debit-card.png"))); // NOI18N
        btnConfirmarPagamento.setText("Confirmar Pagamento");
        btnConfirmarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPagamentoActionPerformed(evt);
            }
        });

        btnConfirmarAssinatura.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnConfirmarAssinatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agreement.png"))); // NOI18N
        btnConfirmarAssinatura.setText("Confirmar assinatura");
        btnConfirmarAssinatura.setEnabled(false);
        btnConfirmarAssinatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarAssinaturaActionPerformed(evt);
            }
        });

        lbTituloStatusContrato.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lbTituloStatusContrato.setText("Status do contrato:");

        lbTituloStatusPagamento.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lbTituloStatusPagamento.setText("Status da taxa de matrícula:");

        btnEmitirContrato.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnEmitirContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agreement.png"))); // NOI18N
        btnEmitirContrato.setText("Emitir contrato          ");
        btnEmitirContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmitirContratoActionPerformed(evt);
            }
        });

        btnEmitirRecibo.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnEmitirRecibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/receipt.png"))); // NOI18N
        btnEmitirRecibo.setText("Emitir recibo              ");
        btnEmitirRecibo.setEnabled(false);
        btnEmitirRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmitirReciboActionPerformed(evt);
            }
        });

        lbStatusPagamentoEscrito.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lbStatusPagamentoEscrito.setForeground(new java.awt.Color(255, 51, 51));
        lbStatusPagamentoEscrito.setText("Pendente");

        lbStatusContratoEscrito.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lbStatusContratoEscrito.setForeground(new java.awt.Color(255, 51, 51));
        lbStatusContratoEscrito.setText("Pendente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbImagem)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmar)
                        .addGap(26, 26, 26))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEmitirRecibo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmitirContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfirmarAssinatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfirmarPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTituloStatusContrato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbStatusContratoEscrito))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTituloStatusPagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbStatusPagamentoEscrito)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbImagem)
                .addGap(21, 21, 21)
                .addComponent(lbAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnEmitirContrato)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTituloStatusContrato)
                            .addComponent(lbStatusContratoEscrito))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTituloStatusPagamento)
                            .addComponent(lbStatusPagamentoEscrito))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnConfirmarAssinatura)
                        .addGap(28, 28, 28)
                        .addComponent(btnConfirmarPagamento)
                        .addGap(27, 27, 27)
                        .addComponent(btnEmitirRecibo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVoltar)
                            .addComponent(btnConfirmar))
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarAssinaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarAssinaturaActionPerformed
        
    }//GEN-LAST:event_btnConfirmarAssinaturaActionPerformed

    private void btnEmitirContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmitirContratoActionPerformed
        
    }//GEN-LAST:event_btnEmitirContratoActionPerformed

    private void btnConfirmarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPagamentoActionPerformed
        
    }//GEN-LAST:event_btnConfirmarPagamentoActionPerformed

    private void btnEmitirReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmitirReciboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmitirReciboActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        MemberRegistrationView memberRegistrationView = new MemberRegistrationView();
        
        memberRegistrationView.setTitle("Adicionar aluno");
        memberRegistrationView.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnConfirmarAssinatura;
    private javax.swing.JButton btnConfirmarPagamento;
    private javax.swing.JButton btnEmitirContrato;
    private javax.swing.JButton btnEmitirRecibo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lbAviso;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JLabel lbStatusContratoEscrito;
    private javax.swing.JLabel lbStatusPagamentoEscrito;
    private javax.swing.JLabel lbTituloStatusContrato;
    private javax.swing.JLabel lbTituloStatusPagamento;
    // End of variables declaration//GEN-END:variables
}
