/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.membercrud;

import controller.MemberListController;
import javax.swing.JOptionPane;

/**
 *
 * @author Jefferson
 */
public class MemberList extends javax.swing.JFrame {

    private MemberListController memberListController;
    /**
     * Creates new form MenuPrincipal
     */
    public MemberList() {
        initComponents();
        memberListController = new MemberListController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImagem = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        lbPesquisarNome = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        scAlunos = new javax.swing.JScrollPane();
        tbAlunos = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JButton();
        lbVisualizarAluno = new javax.swing.JButton();
        lbEditarAluno = new javax.swing.JButton();
        btnRemoverAluno = new javax.swing.JButton();
        lbNovoAluno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        lbImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoPequena.png"))); // NOI18N

        btnVoltar.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        btnVoltar.setText("Voltar");

        lbPesquisarNome.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        lbPesquisarNome.setText("Pesquisar por nome");

        txtPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });

        tbAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbAlunos.getTableHeader().setReorderingAllowed(false);
        scAlunos.setViewportView(tbAlunos);

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        lbVisualizarAluno.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        lbVisualizarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visualize.png"))); // NOI18N
        lbVisualizarAluno.setText("Visualizar aluno");
        lbVisualizarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbVisualizarAlunoActionPerformed(evt);
            }
        });

        lbEditarAluno.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        lbEditarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        lbEditarAluno.setText("Editar aluno");
        lbEditarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbEditarAlunoActionPerformed(evt);
            }
        });

        btnRemoverAluno.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        btnRemoverAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnRemoverAluno.setText("Remover aluno");
        btnRemoverAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverAlunoActionPerformed(evt);
            }
        });

        lbNovoAluno.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 20)); // NOI18N
        lbNovoAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-user.png"))); // NOI18N
        lbNovoAluno.setText("Novo aluno");
        lbNovoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbNovoAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbImagem)
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPesquisarNome)
                            .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(btnPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(scAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbNovoAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbEditarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemoverAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbVisualizarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnVoltar)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbImagem)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbPesquisarNome)
                        .addGap(2, 2, 2)
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnPesquisar)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lbNovoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbVisualizarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbEditarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoverAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(btnVoltar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void lbVisualizarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbVisualizarAlunoActionPerformed
        int id = memberListController.getSelectedMemberId(tbAlunos);
        
        memberListController.visualizeMember(this, id);
    }//GEN-LAST:event_lbVisualizarAlunoActionPerformed

    private void lbEditarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbEditarAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbEditarAlunoActionPerformed

    private void btnRemoverAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverAlunoActionPerformed
        int id = memberListController.getSelectedMemberId(tbAlunos);
        
        int rowsAffected = memberListController.deleteMember(id);
        
        if(rowsAffected > 0){
            JOptionPane.showMessageDialog(null, "Registro excluído com sucesso!");
            System.out.println("Linhas afetadas: "+rowsAffected);
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possível excluir o registro");
        }
    }//GEN-LAST:event_btnRemoverAlunoActionPerformed

    private void lbNovoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbNovoAlunoActionPerformed
        MemberRegistrationView memberRegistrationView = new MemberRegistrationView();
        memberRegistrationView.setTitle("Adicionar aluno");
        memberRegistrationView.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_lbNovoAlunoActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        memberListController.fillMembersTable(tbAlunos, txtPesquisar.getText());
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        memberListController.fillMembersTable(tbAlunos, "");
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRemoverAluno;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton lbEditarAluno;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JButton lbNovoAluno;
    private javax.swing.JLabel lbPesquisarNome;
    private javax.swing.JButton lbVisualizarAluno;
    private javax.swing.JScrollPane scAlunos;
    private javax.swing.JTable tbAlunos;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
